site_name: tnc-event-dispatcher
theme: rtd-dropdown
repo_url: https://github.com/thenetcircle/tnc-event-dispatcher
pages:
  - Overview: index.md
  - Dispatcher: dispatcher.md
  - Serializer: serializer.md
  - EndPoint: endpoint.md
  - Receiver: receiver.md
  - Change Logs: change_logs.md
